### ISSUE TITLE
0430 TODO

### ISSUE THREAD

**Issue by qianz111** [cesame-pl/cesame#13]
- [x]  If while for semantics check;
- [ ]  Struct declaration AST and semantics check (A Struct name should be considered like a type, like C++); Struct definition semantic check (For example, struct member cannot contain itself);
- [x]  New and newable;
- [ ]  Check type for array's element (For example, int_array[i] should have the type of int, not Array<int>
- [ ]  Add break and check if it's in a breakable block (for/while block, if there's a block (That's not a function block) inside of the if/while block, then inherits its breakability. )
- [ ] Semantically check what can be new/deleted. (Only struct, and potentially first-class function.)
- [ ] Add support for "Student a = new Student {...};" I can imagine this being added to the stmt CFG.

**Comment by tengjiang** [comment]
More: 
- [x] a[i] and student.name support (AccessMember and AccessElement)
