### ISSUE TITLE
0501 TODO

### ISSUE THREAD

**Issue by tengjiang** [cesame-pl/cesame#18]
- [ ] Automate testing
- [ ] Check_access_member
- [ ] Check_access_elements
- [ ] Finish up all cases for check_expr and check_stmt
