### ISSUE TITLE
0506 TODO

### ISSUE THREAD

**Issue by tengjiang** [cesame-pl/cesame#22]
- [ ]  Also print out the func-def map and the struct-def list when printing out semantics.
- [ ] Full support for build-in functions.
- [ ] More IRGen (prioritize var declaration and assignment.)
- [ ] Add student.name to symbol list. when checking assign, check the lhs is assignable.
